name: Build Vue to Github Pages
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
      - uses: actions/checkout@v2
      - id: Build-Vue
        uses: xRealNeon/VuePagesAction@1.0.1
        with:
          username: 'milkory'
          reponame: 'idiole'
          token: ${{ secrets.TOKEN }}
          useyarn: true
